### ISSUE TITLE
feat: Home/Back Button after the Display of Results

### ISSUE THREAD

**Issue by bharathkalyans** [Hamza-Khiar/snailotyper#2]
* Having a Home/Back button would be more helpful, rather than going back to the home page using the back functionality of the browser.

<img width="1439" alt="Screenshot 2023-05-30 at 2 43 54 PM" src="https://github.com/Hamza-Khiar/snailotyper/assets/49526472/4e17c6e0-25a6-4a22-b683-c2c74ae7ed1e">

**Comment by Hamza-Khiar** [comment]
hey there thank you for bringing it into my attention,
i just fixed it.
